// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UniversidadeTramontina.Data;
using UniversidadeTramontina.Models;

namespace UniversidadeTramontina.Migrations
{
    [DbContext(typeof(EscolaContexto))]
    [Migration("20180316132332_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversidadeTramontina.Models.Curso", b =>
                {
                    b.Property<int>("CursoID");

                    b.Property<int>("Creditos");

                    b.Property<string>("Titulo");

                    b.HasKey("CursoID");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("UniversidadeTramontina.Models.Estudante", b =>
                {
                    b.Property<int>("EstudanteID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataMatricula");

                    b.Property<string>("Nome");

                    b.Property<string>("SobreNome");

                    b.HasKey("EstudanteID");

                    b.ToTable("Estudante");
                });

            modelBuilder.Entity("UniversidadeTramontina.Models.Matricula", b =>
                {
                    b.Property<int>("MatriculaID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CursoID");

                    b.Property<int>("EstudanteID");

                    b.Property<int?>("Nota");

                    b.HasKey("MatriculaID");

                    b.HasIndex("CursoID");

                    b.HasIndex("EstudanteID");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("UniversidadeTramontina.Models.Matricula", b =>
                {
                    b.HasOne("UniversidadeTramontina.Models.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniversidadeTramontina.Models.Estudante", "Estudante")
                        .WithMany("Matriculas")
                        .HasForeignKey("EstudanteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
